Fix AttributeError: 'NoneType' object has no attribute 'section'
This is caused by packages that have no Section: defined.

Thanks: Matus UHLAR for the Debian bug report (#996035)

Thanks: @garaged for the patch

Closes: rackerlabs/kthresher#86